name: Build Manjii Dylib
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Theos & SDK
        run: |
          # Install Theos secara manual agar lebih stabil di GitHub
          git clone --recursive https://github.com/theos/theos.git ~/theos
          
          # Download SDK iOS 16.5
          curl -LO https://github.com/theos/sdks/raw/master/iPhoneOS16.5.sdk.tar.xz
          
          # Buat folder sdks dan ekstrak filenya
          mkdir -p ~/theos/sdks
          tar -xvf iPhoneOS16.5.sdk.tar.xz -C ~/theos/sdks
          
          # Hapus file tar agar bersih
          rm iPhoneOS16.5.sdk.tar.xz

      - name: Build Dylib
        run: |
          export THEOS=~/theos
          # Jalankan perintah pembersihan dulu sebelum masak
          make clean
          make package

      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: ManjiiDylib-iOS18
          path: packages/*.deb
