name: Build Manjii Dylib Final
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Pasang Dapur Theos
        run: |
          # Install Theos otomatis
          bash -c "$(curl -fsSL https://raw.githubusercontent.com/theos/theos/master/bin/install-theos)"
          
          # Ambil bumbu SDK 16.5
          curl -LO https://github.com/theos/sdks/raw/master/iPhoneOS16.5.sdk.tar.xz
          mkdir -p ~/theos/sdks
          tar -xf iPhoneOS16.5.sdk.tar.xz -C ~/theos/sdks

      - name: Masak Menu Manjii
        run: |
          export THEOS=~/theos
          # Kita paksa build meskipun ada file lama yang nyangkut
          make clean
          make package FINALPACKAGE=1

      - name: Kirim Hasil ke HP Manjii
        uses: actions/upload-artifact@v4
        with:
          name: Menu-Manjii-iOS18
          path: packages/*.deb
